search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
		path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
	path('', views.allProdCat, name='allProdCat'),
	path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
	path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name = 'ProdCatDetail'),
	path('authorized', views.authorized),
]

webstore_008/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from shop import views
from django.conf import settings
from django.conf.urls.static import static

from webstore_008.settings import STATIC_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path('account/authorized/', views.authorized, name='authorized'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
	cart_id = models.CharField(max_length=250, blank=True)
	date_added = models.DateField(auto_now_add=True)
	class Meta:
		db_table = 'Cart'
		ordering = ['date_added']

	def __str__(self):
		return self.cart_id

class CartItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	active = models.BooleanField(default=True)
	class Meta:
		db_table = 'CartItem'

	def sub_total(self):
		return self.product.price * self.quantity

	def __str__(self):
		return self.product

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)
  # https://learndjango.com/tutorials/django-slug-tutorial
	description = models.TextField(blank=True)
	image = models.ImageField(upload_to='category', blank=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_url(self):
		return reverse('shop:products_by_category', args=[self.slug])
		# https://www.educba.com/django-reverse/
    # We could instead "return HttpResponseRedirect('/something/')""
		# But what if you want to change the URL in the future? 
  	# You'd have to update your urls.py and all references to it in your code.

	def __str__(self):
		return '{}'.format(self.name)

class Product(models.Model):
	name = models.CharField(max_length=250, unique=True)
	slug = models.SlugField(max_length=250, unique=True)
	description = models.TextField(blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(upload_to='product', blank=True)
	stock = models.IntegerField()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'product'
		verbose_name_plural = 'products'

	def get_url(self):
		return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])
		# https://www.educba.com/django-reverse/
    # We could instead "return HttpResponseRedirect('/something/')""
		# But what if you want to change the URL in the future? 
  	# You'd have to update your urls.py and all references to it in your code.

	def __str__(self):
		return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=100, required=True)
	last_name = forms.CharField(max_length=100, required=True)
	email = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')

	class Meta:
		model = User
		fields = ('first_name','last_name','email','username','password1','password2')

cart/views.py
from django.shortcuts import render

# Create your views here.

search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def searchResult(request):
	products = None
	query = None
	if 'q' in request.GET:
		query = request.GET.get('q')
    # https://riptutorial.com/django/example/4565/advanced-queries-with-q-objects
    # We can use Q objects to create AND, OR conditions in the lookup query.
		products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    # If the description contains the string, return the result
	return render(request, 'search.html', {'query':query, 'products':products})

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category,Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required, user_passes_test

def index(request):
  return redirect('signin')
 
@login_required(login_url='/admin')
def authorized(request):
  products_list = Product.objects.all()
  return render(request, 'shop/authorized.html', {'products_list': products_list})

def allProdCat(request, c_slug=None):
	c_page = None
	products_list = None
	if c_slug!=None:
		c_page = get_object_or_404(Category,slug=c_slug)
		products_list = Product.objects.filter(category=c_page,available=True)
	else:
		products_list = Product.objects.all().filter(available=True)
	# Give Paginator a list of objects, 
  # plus the number of items you’d like to have on each page, 
  # and it gives you methods for accessing the items for each page
	paginator = Paginator(products_list, 6)
	try:
		page = int(request.GET.get('page','1'))
	except:
		page = 1
	try:
		products = paginator.page(page)
	except (EmptyPage,InvalidPage):
		products = paginator.page(paginator.num_pages)
	return render(request,'shop/category.html',{'category':c_page,'products':products})

def ProdCatDetail(request,c_slug,product_slug):
	try:
		product = Product.objects.get(category__slug=c_slug,slug=product_slug)
	except Exception as e:
		raise e
	return render(request,'shop/product.html', {'product':product})

def signupView(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			signup_user = User.objects.get(username=username)
			customer_group = Group.objects.get(name='Customer')
			customer_group.user_set.add(signup_user)
	else:
		form = SignUpForm()
	return render(request, 'accounts/signup.html', {'form':form})

def signinView(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('shop:allProdCat')
			else:
				return redirect('signup')
	else:
		form = AuthenticationForm()
	return render(request,'accounts/signin.html', {'form':form })

def signoutView(request):
	logout(request)
	return redirect('signin')

search_app/templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	Our jewelry is the finest in the world.
{% endblock %}
{% block title %}
	Search - Webstore
{% endblock %}
{% block content %}
	<div>
		<p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
	</div>
	<div class="container">
		<div class="row mx-auto">
			{% for product in products %}
				<div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
					<div class="card text-center" style="min-width: 18rem;">
						<a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
						<div class="card-body">
							<h4>{{product.name}}</h4>
							<p>${{product.price}}</p>
						</div>
					</div>
				</div>
				{% empty %}
				<div class="row mx-auto">
					<p class="text-center my_search_text">0 results found.</p>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

shop/templates/accounts/signin.html
{% extends "base_login.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign In
{% endblock %}
{% block title %}
	Login - Webstore
{% endblock %}
{% block content %}
	<div class="container">
		<br>
		<h1 class="my_title text-center">Login or Create a New Account</h1>
		<br>
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center my_custom_div">
				<br>
				<h2 class="my_title">New Customer?</h2>
				<br>
				<p>Create an account with us.</p>
				<br>
				<a href="{% url 'signup' %}" class="btn btn-secondary">Create New Account</a>
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 bg-light">
				<div>
					<br>
					<h2 class="my_title">Registered Customers Only</h2>
					<form method="post">
						{% csrf_token %}
						<p>{{ form | crispy }}</p>
						<button type="submit" class="btn btn-secondary">Login</button>
					</form>
					<br>
				</div>
				
			</div>
		</div>
		<br>
	</div>
	<br>
{% endblock %}

shop/templates/accounts/signup.html
{% extends "base_login.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign up for a new account.
{% endblock %}
{% block title %}
	Create a New Account - Webstore
{% endblock %}
{% block content %}
	<div>
		{% if not form.is_valid %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Create a new account</h1>
				<br>
				<div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
					<br>
					<p>Enter the following information to create a new account.</p>
					<form method="post">
						{% csrf_token %}
						<p>{{ form | crispy }}</p>
						<button type="submit" class="btn btn-secondary">Register Account</button>
					</form>
					<br>
				</div>
			</div>
		{% else %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Your account has been successfully created</h1>
				<br>
				<div>
					<p>
						Dear Customer,
						<br>
						<br>
						Your account has been created.
						<br>
						<a href="{% url 'shop:allProdCat' %}">Continue shopping</a>
					</p>
				</div>
			</div>

		{% endif %}
	</div>
	<br>
{% endblock %}

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width = device-width, initial-scale = 1, shrink-to-fit = no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;1,300&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script src="https://kit.fontawesome.com/4716180b0f.js" crossorigin="anonymous"></script>
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: palevioletred;">

    <div class="container">
        <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
            {% include 'top-navbar.html' %}
        </div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <!--
      <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</body>
</html>

shop/templates/base_auth.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width = device-width, initial-scale = 1, shrink-to-fit = no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;1,300&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script src="https://kit.fontawesome.com/4716180b0f.js" crossorigin="anonymous"></script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
<title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: palevioletred;">

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% include 'footer.html' %}
    <!--
      <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</body>
</html>

shop/templates/base_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width = device-width, initial-scale = 1, shrink-to-fit = no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;1,300&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script src="https://kit.fontawesome.com/4716180b0f.js" crossorigin="anonymous"></script>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
<title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: palevioletred;">

    <div class="container">
      <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
        {% include 'top-navbar.html' %}
      </div>
      {% include 'header.html' %}
      {% block content %}
      {% endblock %}
    </div>
    {% include 'footer.html' %}
    <!--
      <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
    -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class = "text-center">&copy; CIS008</p> 
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo1.png' %}" alt = "Webstore Logo"></a>
	</center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul>
        
        <li>
            <a href="{% url 'shop:allProdCat' %}">All Products</a>
        </li>

          {% for cat in links %}
            <li style="display:inline"><a href="{{cat.get_url}}">{{cat.name}}</a></li>
          {% endfor %}
        
      <li class="nav-item">
          <a class="nav-link" href="#">Shopping Cart<i class="fas fa-shopping-cart"></i></a>
      </li>

    </ul>

    <form style="margin: auto; width: 220px;" class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>

    


  </div>
</nav>

shop/templates/shop/authorized.html
{% extends "base_auth.html" %}
{% load staticfiles %}
{% block content %}
<html>
  <a href="{% url 'shop:allProdCat' %}">Back to Shopping Area</a>
  <h1>Jewelry Store Administrator Page</h1>
  <div class="table-responsive">
    <caption><h3>Product Report</h3></caption>
  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th scope="col">Product Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity in Stock</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products_list %}
      <tr>
        <td><b>{{product.name}}</b></td>
        <td><b>{{product.price}}</b></td>
        <td><b>{{product.stock}}</b></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
{% endblock %}

shop/templates/shop/category.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
  {% if category %}
    {{ category.description | truncatewords:155 }}
  {% else %}
    Welcome to the Webstore
  {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
    {{ category.name }} - Webstore
  {% else %}
  Find All Our Jewelry at the Webstore
  {% endif %}
{% endblock %}
{% block content %}
 <div>
	{% if category %}
		<div class="row my_row_class">
			<div class="mx-auto">
				<p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a> | {{category.name}}</p>
			</div>
		</div>
	{% endif %}
	<div class="mx-auto">
    {% if category %}
      <img class="img-fluid" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
      <h1 class="text-center my_title">{{category.name}}</h1>
      <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
      <img class="my_image my_image_padding" src="{% static 'img/banner1.jpg' %}" alt="Our Products Collection">
  </div>
  <br>
  <div>
    <h1>Our Products Collection</h1>
    <p>You have many choices for buying jewelry, but our quality is the best.</p>
  </div>
  {% endif %}
  
	<div class="container">
		<div class="row mx-auto">
			{% for product in products.object_list %}
				<div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
					<div class="card text-center" style="min-width: 18rem;">
						<a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
						<div class="card-body">
							<h4>{{product.name}}</h4>
							<p>${{product.price}}</p>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<div class="mx-auto">
			{% if products.paginator.num_pages > 1 %}
				<hr>
				<div class="text-center">
					{% for pg in products.paginator.page_range %}
						<a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
					{% endfor %}
				</div>
			{% endif %}
		</div>
		<br>
	</div>
{% endblock %}

shop/templates/shop/product.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	{{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
	{{ product.name }} - Webstore
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
  <div class="mx-auto">
    <p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name}}</p>
  </div>
		<div class="container">
			<br>
			<div class="row">
				<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
					<div style="min-width: 18rem;">
						<img src="{{product.image.url}}" alt="{{product.name}}">
					</div>
				</div>
				<div class="col-12 col-sm-12 col-md-12 col-lg-6">
					<div>
						<h1 class="my_prod_title">{{product.name}}</h1>
						<p>${{product.price}}</p>
						<p class="my_title">Product Description</p>
						<p class="text-justify my_prod_text">{{product.description}}</p>
						{% if product.stock <= 0 %}
							<p class="text-justify my_prod_text"><b>Out of Stock</b></p>
						{% else %}
							<a class="btn btn-secondary" href="">Add to Cart</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

shop/templates/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %}
			<li>
				Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} <i class="fas fa-user-circle"></i></a>
			</li>
			<li>
				<a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
			</li>

			{% endif %}
		</ul>
		
	</div>
</div>